### ISSUE TITLE
Default features.

### ISSUE THREAD

**Issue by n3vu0r** [arcnmx/i2c-linux-rs#2]
Consider making `i2c` and `udev` default features or give a hint in the documentation. [Here](https://docs.rs/i2c-linux) it is difficult to find these features.

**Comment by arcnmx** [comment]
Not a fan of default features, particularly ones that pull in dependencies. `[package.metadata.docs.rs]` can be used in the Cargo.toml to tell docs.rs to document all features at least, though yeah, a note about the `i2c` feature could probably be added to the crate-level documentation.
